"use client";

import { useState, type ReactNode } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Bell, BookOpen, BrainCircuit, ChevronRight, Compass, FileText, Galaxy, GraduationCap, Menu, Orbit, Play, Search, Sparkles, Telescope, Users, X, type LucideIcon } from "lucide-react";

const nav = ["Research", "Explore", "AstroFlix", "Library", "Community"];
const features: { icon: LucideIcon; title: string; description: string }[] = [
  { icon: BrainCircuit, title: "AI Research Copilot", description: "Understand figures, uncover links, and surface what matters." },
  { icon: Telescope, title: "Smart Discovery", description: "Search images, papers and observations with visual AI." },
  { icon: Users, title: "Cosmic Network", description: "Meet mentors, collaborators and fellow explorers." },
  { icon: GraduationCap, title: "Learn Without Limits", description: "From first light to frontier research, at your pace." },
];
const ecosystemLinks: { icon: LucideIcon; title: string; description: string }[] = [
  { icon: BookOpen, title: "Knowledge Hub", description: "Stories, courses, theory explainers." },
  { icon: Play, title: "AstroFlix", description: "Watch the universe unfold." },
  { icon: FileText, title: "Research Lab", description: "Publish, review, collaborate." },
  { icon: Users, title: "Global community", description: "Find your constellation." },
];
const stats = [["12.4K", "Research papers mapped"], ["1.8K", "Researchers connected"], ["98.6%", "AI matching accuracy"], ["160+", "Celestial events tracked"]];
const papers = [
  ["JWST reveals a cosmic dawn", "Dr. Maya Chen · Astrophysics", "Galaxy formation", "97%"],
  ["Mapping dark matter with lensing", "Prof. Aaron Reeves · Cosmology", "Dark matter", "94%"],
  ["A new view of Andromeda", "Elena Vasquez · Observational", "Deep sky", "91%"],
];
const activities = [["New paper match", "Gravitational-wave echoes", "2 min ago", "#8b5cf6"], ["Event reminder", "Perseid meteor shower", "Tomorrow · 02:00", "#06b6d4"], ["Mentor response", "Dr. Amara Okafor replied", "1 hr ago", "#f59e0b"]];

function Pill({ children }: { children: ReactNode }) { return <span className="rounded-full border border-cyan/20 bg-cyan/10 px-3 py-1 text-xs text-cyan">{children}</span> }
function Button({ children, secondary = false }: { children: ReactNode; secondary?: boolean }) { return <button type="button" className={`group inline-flex items-center justify-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold transition ${secondary ? "border border-white/15 bg-white/5 hover:bg-white/10" : "bg-gradient-to-r from-cosmic to-galaxy shadow-[0_0_28px_rgba(108,99,255,.38)] hover:brightness-110"}`}>{children}</button> }

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [search, setSearch] = useState("");
  return <main className="min-h-screen"><header className="fixed inset-x-0 top-0 z-50 border-b border-white/5 bg-space/70 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5"><a href="#" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-cyan to-cosmic shadow-[0_0_22px_rgba(6,182,212,.4)]"><Orbit size={21}/></span><span>AstroVerse <i className="font-normal text-cyan">AI</i></span></a><nav className="hidden items-center gap-7 text-sm text-slate-300 md:flex">{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`} className="transition hover:text-white">{x}</a>)}</nav><div className="hidden items-center gap-3 md:flex"><button aria-label="Notifications" className="rounded-lg p-2 text-slate-300 hover:bg-white/10"><Bell size={19}/></button><Button secondary>Sign in</Button><Button>Get started <ArrowRight size={16}/></Button></div><button aria-label="Open menu" onClick={()=>setMobileOpen(!mobileOpen)} className="md:hidden">{mobileOpen?<X/>:<Menu/>}</button></div>{mobileOpen&&<div className="border-t border-white/10 p-5 md:hidden"><div className="flex flex-col gap-4 text-slate-300">{nav.map(x=><a key={x} href="#features">{x}</a>)}<Button>Get started</Button></div></div>}</header>

  <section className="relative isolate overflow-hidden px-5 pb-24 pt-36"><div className="absolute left-[8%] top-40 h-64 w-64 rounded-full bg-cosmic/20 blur-[110px] animate-drift"/><div className="absolute right-[8%] top-24 h-72 w-72 rounded-full bg-cyan/15 blur-[120px] animate-drift"/><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}><Pill><Sparkles className="mr-1 inline" size={13}/>THE INTELLIGENCE LAYER FOR SPACE</Pill><h1 className="mt-6 max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-7xl">Explore the <span className="bg-gradient-to-r from-cyan via-blue-300 to-cosmic bg-clip-text text-transparent">Universe</span><br/>with AI.</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-400">One intelligent platform for astronomy research, learning, entertainment and a global community of cosmic minds.</p><div className="mt-9 flex flex-wrap gap-3"><Button>Start exploring <ArrowRight size={16}/></Button><Button secondary><Compass size={16}/> Explore research</Button></div><div className="mt-12 flex items-center gap-4"><div className="flex -space-x-2">{["M","R","S","K"].map((x,i)=><span key={x} className="grid h-8 w-8 place-items-center rounded-full border-2 border-space bg-gradient-to-br from-indigo-400 to-cyan-400 text-xs font-bold" style={{filter:`hue-rotate(${i*45}deg)`}}>{x}</span>)}</div><p className="text-sm text-slate-400"><b className="text-white">20,000+</b> explorers discovering together</p></div></motion.div>
  <motion.div initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{delay:.15,duration:.8}} className="relative mx-auto w-full max-w-[570px]"><div className="absolute -inset-10 rounded-full bg-cosmic/20 blur-[75px]"/><div className="glass glow-border relative overflow-hidden rounded-[28px] p-4"><div className="grid-bg absolute inset-0 opacity-30"/><div className="relative rounded-2xl border border-white/10 bg-[#090d27]/80 p-5"><div className="flex items-center justify-between"><div><p className="text-xs text-slate-400">LIVE CELESTIAL ANALYSIS</p><h2 className="mt-1 text-xl font-semibold">Andromeda Galaxy</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan/10 text-cyan"><Telescope size={20}/></span></div><div className="relative mt-5 h-48 overflow-hidden rounded-xl bg-[radial-gradient(ellipse_at_center,#cedbff_0%,#7584d7_8%,#483591_20%,#10102c_45%,#070918_71%)]"><div className="absolute left-[48%] top-1/2 h-36 w-72 -translate-x-1/2 -translate-y-1/2 rotate-[-15deg] rounded-[50%] border border-blue-200/25 shadow-[0_0_30px_12px_rgba(103,91,255,.32)]"/><div className="absolute bottom-3 left-3 rounded-lg border border-white/10 bg-space/70 px-3 py-2 text-xs backdrop-blur"><span className="text-cyan">●</span> JWST NIRCam</div></div><div className="mt-5 grid grid-cols-3 gap-3"><div><p className="text-xs text-slate-500">DISTANCE</p><p className="mt-1 font-semibold">2.5M ly</p></div><div><p className="text-xs text-slate-500">MATCH</p><p className="mt-1 font-semibold text-cyan">97.8%</p></div><div><p className="text-xs text-slate-500">PAPERS</p><p className="mt-1 font-semibold">4,218</p></div></div></div></div><div className="absolute -bottom-6 -left-5 glass animate-float rounded-xl p-3 text-sm"><p className="text-xs text-slate-400">AI insight</p><p className="mt-1 font-medium">3 new correlations found</p></div></motion.div></div></section>

  <section id="features" className="mx-auto max-w-7xl px-5 py-20"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Pill>ONE EXPANSIVE ECOSYSTEM</Pill><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Your universe, connected.</h2></div><p className="max-w-md text-slate-400">Every part of your astronomical journey in one focused, beautifully intelligent workspace.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{features.map(({ icon: Icon, title, description }, index) => <motion.article whileHover={{ y: -6 }} key={title} className={`glass rounded-2xl p-6 ${index === 0 ? "lg:col-span-2 lg:row-span-2" : ""}`}><span className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-cosmic/35 to-cyan/20 text-cyan"><Icon size={22}/></span><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-400">{description}</p><button type="button" className="mt-6 inline-flex items-center gap-1 text-sm font-medium text-cyan">Explore <ChevronRight size={15}/></button></motion.article>)}</div></section>

  <section id="research" className="mx-auto max-w-7xl px-5 py-16"><div className="glass overflow-hidden rounded-[28px]"><div className="grid lg:grid-cols-[.8fr_1.2fr]"><div className="p-7 sm:p-10"><Pill>AI SMART SEARCH</Pill><h2 className="mt-5 text-3xl font-semibold tracking-tight">Ask the cosmos anything.</h2><p className="mt-4 text-slate-400">Search across images, captions, papers and telescope observations—like Google Lens for the universe.</p><div className="mt-7 rounded-xl border border-white/10 bg-space/60 p-2"><div className="flex items-center gap-3 px-3"><Search className="text-cyan" size={19}/><input aria-label="Search astronomy research" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try “spiral galaxies with active nuclei”" className="w-full bg-transparent py-3 text-sm outline-none placeholder:text-slate-500"/><button className="rounded-lg bg-cosmic px-3 py-2 text-xs">Search</button></div></div><div className="mt-6 flex flex-wrap gap-2">{["Upload a figure","Caption analysis","Similarity graph"].map(x=><span className="rounded-md bg-white/5 px-3 py-2 text-xs text-slate-300" key={x}>{x}</span>)}</div></div><div className="relative min-h-[350px] overflow-hidden border-t border-white/10 p-6 lg:border-l lg:border-t-0"><div className="absolute right-4 top-4 h-40 w-40 rounded-full bg-cyan/10 blur-[55px]"/><div className="relative"><div className="flex items-center justify-between"><p className="text-sm font-medium">Suggested matches</p><span className="text-xs text-slate-500">Visual similarity</span></div><div className="mt-5 space-y-3">{papers.map((p,i)=><div key={p[0]} className="flex items-center gap-4 rounded-xl border border-white/8 bg-white/[.035] p-3 transition hover:bg-white/[.08]"><div className={`h-14 w-14 shrink-0 rounded-lg bg-gradient-to-br ${i===0?"from-indigo-300 via-blue-600 to-space":i===1?"from-cyan-300 via-blue-500 to-space":"from-fuchsia-300 via-indigo-700 to-space"}`}></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{p[0]}</p><p className="mt-1 text-xs text-slate-500">{p[1]}</p><span className="mt-2 inline-block text-[11px] text-cyan">{p[2]}</span></div><b className="text-sm text-cyan">{p[3]}</b></div>)}</div></div></div></div></div></section>

  <section className="mx-auto max-w-7xl px-5 py-20"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([n,t])=><div className="rounded-2xl border border-white/8 bg-white/[.025] p-6" key={t}><p className="text-3xl font-semibold tracking-tight">{n}</p><p className="mt-2 text-sm text-slate-400">{t}</p></div>)}</div></section>

  <section id="community" className="mx-auto max-w-7xl px-5 pb-24"><div className="grid gap-6 lg:grid-cols-[1fr_.82fr]"><div className="glass rounded-[28px] p-7 sm:p-9"><div className="flex items-start justify-between"><div><Pill>FOR THE CURIOUS & BRILLIANT</Pill><h2 className="mt-5 text-3xl font-semibold tracking-tight">Built around your next discovery.</h2></div><Galaxy className="text-cyan"/></div><div className="mt-8 grid gap-3 sm:grid-cols-2">{ecosystemLinks.map(({ icon: Icon, title, description }) => <div key={title} className="rounded-xl border border-white/8 bg-space/40 p-4"><Icon className="text-indigo-300" size={18}/><p className="mt-3 font-medium">{title}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div>)}</div></div><div className="glass rounded-[28px] p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-medium">Orbit updates</p><p className="mt-1 text-xs text-slate-500">Keep pace with your universe</p></div><Bell className="text-cyan" size={20}/></div><div className="mt-7 space-y-5">{activities.map(([a,b,c,d])=><div className="flex gap-3" key={a}><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full" style={{backgroundColor:d}}></span><div><p className="text-sm font-medium">{a}</p><p className="mt-1 text-sm text-slate-400">{b}</p><p className="mt-1 text-xs text-slate-600">{c}</p></div></div>)}</div><button type="button" className="mt-8 w-full rounded-xl border border-white/10 py-3 text-sm text-slate-300 transition hover:bg-white/5">View notification center</button></div></div></section>

  <footer className="border-t border-white/8 px-5 py-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-7 text-sm text-slate-500 md:flex-row"><div><div className="flex items-center gap-2 text-base font-bold text-white"><Orbit className="text-cyan" size={18}/> AstroVerse AI</div><p className="mt-2">The intelligent way to explore space.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3"><a href="#">About</a><a href="#">Contact</a><a href="#">Privacy</a><a href="#">Terms</a><a href="#">GitHub</a><a href="#">LinkedIn</a></div><p>© 2026 AstroVerse AI</p></div></footer></main>
}
